apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "imagegram.app.name" . }}
  namespace: imagegram-{{.Values.environment}}
  labels:
    app.kubernetes.io/name: {{ include "imagegram.app.name" . }}
spec:
  replicas: {{.Values.numberOfReplicas}}
  strategy:
    {{- toYaml .Values.scaling_strategy | nindent 4 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "imagegram.app.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "imagegram.app.name" . }}
    spec:
      containers:
        - name: {{ include "imagegram.app.name" . }}
          image: {{ .Values.docker.imageName }}:{{ .Values.docker.imageTag }}
          imagePullPolicy: {{ .Values.docker.imagePullPolicy }}
          ports:
            - containerPort: 8080
          resources:
            {{- toYaml .Values.docker.resources | nindent 12 }}
