apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "imagegram.app.name" . }}-ingress
  namespace: imagegram-{{.Values.environment}}
  labels:
    app.kubernetes.io/name: {{ include "imagegram.app.name" . }}-ingress
spec:
  ingressClassName: nginx-external
  rules:
    - host: {{.Values.subdomain}}.{{.Values.deployment_host}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "imagegram.app.name" . }}
                port:
                  number: 8080