application_name: imagegram
scaling_strategy:
  type: RollingUpdate
environment: prod
numberOfReplicas: 2
subdomain: imagegram
deployment_host: test.aleksandar.com
docker:
  imageName: hub.docker.com/r/acekorg/imagegram
  imageTag: latest
  imagePullPolicy: Always
  resources:
    requests:
      memory: 300Mi
      cpu: 150m
    limits:
      memory: 500Mi
      cpu: 300m